version: '2'
services:
  postgresql:
    image: postgres:12.3
    volumes:
    - ./DB:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
